### ISSUE TITLE
Colour Options

### ISSUE THREAD

**Issue by WeirdScienceX** [amur-tiger/fanfiction-enhancements#101]
Nice script, would it be possible to have an option for more muted colours?

**Comment by amur-tiger** [comment]
Are you referring to the tag colors? In light or in dark mode?
I'd say yes generally, though I'd have to think on a palette.

**Comment by WeirdScienceX** [comment]
Yes, the tags themselves, more of a dark theme, on an HDR monitor especially they are very bright
