### ISSUE TITLE
Fonts do not load on page load

### ISSUE THREAD

**Issue by amur-tiger** [amur-tiger/fanfiction-enhancements#44]
Fonts do not load on page load, causing the page to be rendered using the default serif font. Maybe only an issue on Firefox. Opening the font settings dialog fixes the font. Possibly related console log:

```
Die Ressource von "https://fonts.googleapis.com/css?family=Verdana%7COpen+Sans" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
```

**Comment by amur-tiger** [comment]
Explicitly adding the Google stylesheets for the relevant fonts seems to fix it. Todo: List possible fonts so all can get preloaded.

**Comment by kolbdog3333** [comment]
How do you add the Google stylesheets for the relevant fonts manually

**Comment by kolbdog3333** [comment]
and add new google style imports manually

**Comment by amur-tiger** [comment]
Basically, you need to insert a new link element into the header that links to the Google fonts. Something like this:
```js
      const st = document.createElement("link");
      st.setAttribute("rel", "stylesheet");
      st.setAttribute("href", "https://fonts.googleapis.com/css?family=Open+Sans%7CDroid+Sans%7CPT+Sans%7CUbuntu%7CRoboto");
      st.setAttribute("media", "all");
      document.head.appendChild(st);
```

For this ticket, I still need to enumerate what fonts are actually needed, whenever I get around to it.

**Comment by amur-tiger** [comment]
Available fonts in the Fontastic Panel:
* Arial
* Droid Sans
* Georgia
* Helvetica
* Open Sans
* Palatino
* PT Sans
* Roboto
* Times New Roman
* Ubuntu
* Verdana

**Comment by amur-tiger** [comment]
See also: https://github.com/google/fonts/issues/2214

Only some of the listed fonts exist on Google Fonts:
- [ ] Arial
- [ ] Droid Sans
- [ ] Georgia
- [ ] Helvetica
- [x] Open Sans
- [ ] Palatino
- [x] PT Sans
- [x] Roboto
- [ ] Times New Roman
- [x] Ubuntu
- [ ] Verdana

If the font does not exist, 403 is returned.
