### ISSUE TITLE
Dark Mode support

### ISSUE THREAD

**Issue by amur-tiger** [amur-tiger/fanfiction-enhancements#72]
Current colors don't mesh well with dark mode. Add support for dark mode colors and light/dark mode switching.

**Comment by mastafrooper** [comment]
I kind of take it by this point this isn't happening?

A shame. I really liked this but light mode burns my eyes.

**Comment by amur-tiger** [comment]
I wrote the userscript mainly for myself, and I sadly don't have much time between this and some other projects.

But hearing that others find my script useful does raise my motivation. I'll see if I can fix this over the weekend.

**Comment by mastafrooper** [comment]
You sir, are a gentleman and a scholar.
