### ISSUE TITLE
FFN forgets font settings

### ISSUE THREAD

**Issue by amur-tiger** [amur-tiger/fanfiction-enhancements#79]
Font settings are reset every so often. Also, the cookie banner gets shown again. Might be an unwanted interaction with some addons. Maybe replace font settings entirely?

**Comment by fanficfan** [comment]
> Maybe replace font settings entirely?

Yes please...the over all layout looks amazing and very modern but when reading the story width under the font setting  gives the options for 100, 75, or 50. If there was the option for 40 added to that it would be very nice. The 50% width I have always found to be just a bit to wide so I have to resize the browser but that then destroys the look of the story card at the top of the page. I tried other userscripts but they to just change the width of the whole page not just the story text.
